### ISSUE TITLE
How to Launch simulation without zed camera

### ISSUE THREAD

**Issue by SuYouge** [rpanther/panther_simulation#8]
Hi developer, 
I want to try this robot in gazebo, but I dont have zed camera
I did not compile `zed-ros-wrapper` because my computer does not support cuda.
**How can i use gazebo fake camera instead or just diable this zed camera?**
when I try to launch like 
`roslaunch panther_gazebo empty_world.launch`
it outputs this 

```bash
resource not found: zed_wrapper
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/yogurtsuee/catkin_path/src
ROS path [2]=/home/yogurtsuee/catkin_aslam/src
ROS path [3]=/home/yogurtsuee/ROS/catkin_turtlebot/src
ROS path [4]=/opt/ros/melodic/share
when processing file: /home/yogurtsuee/catkin_path/src/panther/panther_description/urdf/robot.urdf.xacro
included from: /home/yogurtsuee/catkin_path/src/panther/panther_gazebo/urdf/panther.gazebo.xacro
RLException: while processing /home/yogurtsuee/catkin_path/src/panther/panther_gazebo/launch/spawn_robot.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [['/opt/ros/melodic/lib/xacro/xacro', '/home/yogurtsuee/catkin_path/src/panther/panther_gazebo/urdf/panther.gazebo.xacro', 'name_space:=/', 'camera_name:=zed', 'depth_camera:=left', 'resolution:=HD720']] returned with code [2]. 

Param xml is <param command="$(find xacro)/xacro '$(find panther_gazebo)/urdf/panther.gazebo.xacro'               name_space:=/$(arg namespace)               camera_name:=$(arg camera_name)               depth_camera:=$(arg depth_camera)               resolution:=$(arg resolution)" name="robot_description"/>
The traceback for the exception was written to the log file
```

Thank you very much.

**Comment by SuYouge** [comment]
I removed some launch command and it works fine.

**Comment by rbonghi** [comment]
Hi @SuYouge ,

I apologize for my late reply. Yes, is an in-progress work. I temporary added the ros zed package (use my fork to extract the xacro ZED urdf file). I will remove today and will be simple to use.

PS: I reopen again this issue

**Comment by SuYouge** [comment]
Hi @rbonghi , thanks for your help!

**Comment by rbonghi** [comment]
Fixed! Now you can run this simulation without the zed camera package.

My documentation is in progress, anyway you can use

* **simulation.rosinstall** to setup your workspace and download all dependencies 
* At this time is needed a joystick to drive the robot (or you can add an extra node to manage by keyboard)
* Output in RVIZ with: `roslaunch panther_comm display.launch`

For any issues write me.

**Comment by SuYouge** [comment]
Thank yout! @rbonghi
